services:
  redis:
    image: redis/redis-stack:latest
    platform: linux/amd64
    ports:
      - "6379:6379"  # Redis port
      - "8001:8001"  # RedisInsight port
    volumes:
      - ./data/redis:/data
    environment:
      - REDIS_ARGS=--dir /data --appendonly no --save 1800 1
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"    # Jaeger agent UDP
      - "6832:6832/udp"    # Jaeger agent UDP
      - "5778:5778"        # Configs
      - "16686:16686"      # Jaeger UI
      - "14268:14268"      # Collector HTTP
      - "14250:14250"      # gRPC
      - "4317:4317"        # OTLP gRPC
      - "4318:4318"        # OTLP HTTP
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    ports:
      - "9090:9090"
    restart: unless-stopped
